URL = "https://offset.climateneutralnow.org/footprintresult"

HOUSEHOLD = {
    "HouseholdViewModel.HouseholdSize": [i for i in range(1, 13, 1)],
    "HouseholdViewModel.SelectedResidenceCountryId": [35, 33, 45, 72, 80],
    #"HouseholdViewModel.HousingSize": [i for i in range(25, 1000, 10)],
    "HouseholdViewModel.SelectedHousingTypeOptionId": [1, 2, 3, 4],
    
    "HouseholdViewModel.NotKnownElectricityConsumption": [True, False],
    "HouseholdViewModel.ElectricityConsumption": [i for i in range(500, 1800, 200)],
    #"HouseholdViewModel.UsageLightbulbs": [True, False],
    #"HouseholdViewModel.UsageEnergyStar": [True, False],
    #"HouseholdViewModel.UsageThermostat": [True, False],
    #"HouseholdViewModel.UsageEnergySavingDevices": [True, False],
    #"HouseholdViewModel.UsageSolarWaterHeater": [True, False],
    
    "HouseholdViewModel.CleanSource": [i for i in range(0, 100, 10)],
    "HouseholdViewModel.SelectedHeatingSourceOptionId": [5, 6, 7, 8, 9, 10, 11, 12, 13],
}

TRANSPORT = {
    #"TransportViewModel.Intercity": [i for i in range(1, 10)],
    #"TransportViewModel.Subway": [i for i in range(1, 10)],
    #"TransportViewModel.Bus": [i for i in range(1, 4)],
    #"TransportViewModel.CityBus": [i for i in range(1, 4)],
    #"TransportViewModel.Tram": [i for i in range(1, 10)],
    #"TransportViewModel.BikeWalk": [i for i in range(7, 15)],
    
    "TransportViewModel.CarUsageList[0].SelectedFuelTypeOptionId": [15, 16, 17, 18],
    "TransportViewModel.CarUsageList[0].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.CarUsageList[0].AverageConsumption": [i for i in range(6, 10, 1)],
    
    "TransportViewModel.CarUsageList[1].SelectedFuelTypeOptionId": [15, 16, 17, 18],
    "TransportViewModel.CarUsageList[1].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.CarUsageList[1].AverageConsumption": [i for i in range(6, 10, 1)],
    
    "TransportViewModel.CarUsageList[2].SelectedFuelTypeOptionId": [15, 16, 17, 18],
    "TransportViewModel.CarUsageList[2].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.CarUsageList[2].AverageConsumption": [i for i in range(6, 10, 1)],
    
    "TransportViewModel.CarUsageList[3].SelectedFuelTypeOptionId": [15, 16, 17, 18],
    "TransportViewModel.CarUsageList[3].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.CarUsageList[3].AverageConsumption": [i for i in range(6, 10, 1)],

    "TransportViewModel.CarUsageList[4].SelectedFuelTypeOptionId": [15, 16, 17, 18],
    "TransportViewModel.CarUsageList[4].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.CarUsageList[4].AverageConsumption": [i for i in range(6, 10, 1)],
    
    "TransportViewModel.MotorbikeUsageList[0].SelectedFuelTypeOptionId": [31, 32],
    "TransportViewModel.MotorbikeUsageList[0].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.MotorbikeUsageList[0].AverageConsumption": [3, 4],
    
    "TransportViewModel.MotorbikeUsageList[1].SelectedFuelTypeOptionId": [31, 32],
    "TransportViewModel.MotorbikeUsageList[1].AnnualMileage": [i for i in range(10000, 16000, 1000)],
    "TransportViewModel.MotorbikeUsageList[1].AverageConsumption": [3, 4],
    
    "TransportViewModel.VeryLongRangeFlight": [0, 0, 0, 0, 0, 1, 1, 1, 1, 2],
    "TransportViewModel.LongRangeFlight": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3],
    "TransportViewModel.MediumRangeFlight": [i for i in range(0, 4)],
    "TransportViewModel.ShortRangeFlight": [0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5],
}

LIFESTYLE = {
    "LifestyleViewModel.SelectedDietOptionId": [19, 20, 21, 22, 23],
    "LifestyleViewModel.SelectedLocalProductsOptionId": [24, 25, 26],
    "LifestyleViewModel.SelectedResponsibleCompaniesOptionId": [28, 29, 30],
    "LifestyleViewModel.MealsOut": [0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
    "LifestyleViewModel.RecycleFood": [True, False],
    "LifestyleViewModel.RecyclePaper": [True, False],
    "LifestyleViewModel.RecycleTinCans": [True, False],
    "LifestyleViewModel.RecyclePlastic": [True, False],
    "LifestyleViewModel.RecycleGlass": [True, False]
}

FORM = {**HOUSEHOLD, **TRANSPORT, **LIFESTYLE}

COLUMNS = [
    "datetime",
    
    "HouseholdViewModel.HouseholdSize",
    "HouseholdViewModel.SelectedResidenceCountryId",
    "HouseholdViewModel.HousingSize",
    "HouseholdViewModel.SelectedHousingTypeOptionId",
    "HouseholdViewModel.NotKnownElectricityConsumption",
    "HouseholdViewModel.ElectricityConsumption",
    "HouseholdViewModel.UsageLightbulbs",
    "HouseholdViewModel.UsageEnergyStar",
    "HouseholdViewModel.UsageThermostat",
    "HouseholdViewModel.UsageEnergySavingDevices",
    "HouseholdViewModel.UsageSolarWaterHeater",
    "HouseholdViewModel.CleanSource",
    "HouseholdViewModel.SelectedHeatingSourceOptionId",
    
    "TransportViewModel.Intercity",
    "TransportViewModel.Subway",
    "TransportViewModel.Bus",
    "TransportViewModel.CityBus",
    "TransportViewModel.Tram",
    "TransportViewModel.BikeWalk",
    "TransportViewModel.CarUsageList[0].SelectedFuelTypeOptionId",
    "TransportViewModel.CarUsageList[0].AnnualMileage",
    "TransportViewModel.CarUsageList[0].AverageConsumption",
    "TransportViewModel.CarUsageList[1].SelectedFuelTypeOptionId",
    "TransportViewModel.CarUsageList[1].AnnualMileage",
    "TransportViewModel.CarUsageList[1].AverageConsumption",
    "TransportViewModel.CarUsageList[2].SelectedFuelTypeOptionId",
    "TransportViewModel.CarUsageList[2].AnnualMileage",
    "TransportViewModel.CarUsageList[2].AverageConsumption",
    "TransportViewModel.CarUsageList[3].SelectedFuelTypeOptionId",
    "TransportViewModel.CarUsageList[3].AnnualMileage",
    "TransportViewModel.CarUsageList[3].AverageConsumption",
    "TransportViewModel.CarUsageList[4].SelectedFuelTypeOptionId",
    "TransportViewModel.CarUsageList[4].AnnualMileage",
    "TransportViewModel.CarUsageList[4].AverageConsumption",
    "TransportViewModel.MotorbikeUsageList[0].SelectedFuelTypeOptionId",
    "TransportViewModel.MotorbikeUsageList[0].AnnualMileage",
    "TransportViewModel.MotorbikeUsageList[0].AverageConsumption",
    "TransportViewModel.MotorbikeUsageList[1].SelectedFuelTypeOptionId",
    "TransportViewModel.MotorbikeUsageList[1].AnnualMileage",
    "TransportViewModel.MotorbikeUsageList[1].AverageConsumption",
    "TransportViewModel.VeryLongRangeFlight",
    "TransportViewModel.LongRangeFlight",
    "TransportViewModel.MediumRangeFlight",
    "TransportViewModel.ShortRangeFlight",
    
    "LifestyleViewModel.SelectedDietOptionId",
    "LifestyleViewModel.SelectedLocalProductsOptionId",
    "LifestyleViewModel.SelectedResponsibleCompaniesOptionId",
    "LifestyleViewModel.MealsOut",
    "LifestyleViewModel.RecycleFood",
    "LifestyleViewModel.RecyclePaper",
    "LifestyleViewModel.RecycleTinCans",
    "LifestyleViewModel.RecyclePlastic",
    "LifestyleViewModel.RecycleGlass",
    
    "total_annual", 
    "country_average",
    "world_average",
    "household",
    "transport",
    "flights",
    "lifestyle"
]

HEADERS = [{'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'Upgrade-Insecure-Requests': '1',
     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc', 
     'User-Agent': 'Mozilla/5.0 (Android 4.4; Tablet; rv:41.0) Gecko/41.0 Firefox/41.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Windows NT x.y; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Windows NT x.y; Win64; x64; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Macintosh; PPC Mac OS X x.y; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0) Gecko/20100101 Firefox/10.0 Fennec/10.0'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/7.0.4 Mobile/16B91 Safari/605.1.15'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
     'User-Agent': 'Mozilla/5.0 (iPod touch; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (iPad; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/44.0.2403.155 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2226.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'},
    {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'DNT': '1',
    'Host': 'offset.climateneutralnow.org',
    'Origin': 'https://offset.climateneutralnow.org',
    'Referer': 'https://offset.climateneutralnow.org/footprintcalc',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36'}]
